<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fa00174b-b7b4-4d17-9c62-54f835d5a3fe</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>{"//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[5]/div[1]/div[1]/input[1]":["#\\:r6\\:"]}</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>