<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>899f333c-cdeb-4eaf-8e90-8da8d5429d14</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_7</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>{"//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[7]/div[1]/div[1]/input[1]":["#\\:r8\\:"]}</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>