<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>99ea79d7-083e-45fb-933a-964b1c29df0f</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>{"//body/div[3]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/button[2]":[":root &gt; :nth-child(2) &gt; :nth-child(12) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(3) &gt; :nth-child(1) &gt; :nth-child(3)"]}</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>