<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7a9bc5bb-32c5-4179-9cf4-b5c95eddeb9f</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>{"//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]":[".swiper-slider__slide.swiper-slide-active .swiper-slider__content"]}</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>