<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a246795d-847d-4da1-bea0-439400618136</elementGuidId>
    <imagePath></imagePath>
    <name>dlya_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>{"//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[4]/ul[1]/li[1]/a[1]":[".horizontal-menu__element[href='\\/category\\/dlya-devushek']"]}</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>