<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6f2562e4-bf4d-49fc-8e18-22ff5b4de016</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>{"//body/div[1]/div[3]/header[1]/section[1]/div[1]/div[3]/a[1]":["[data-traffic-agent-last-action-id='c83ee3ec-03ae-4970-97e0-c0308d72c7f1']"]}</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>