<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bb591fe3-0ff9-4efa-b8dc-8e819579eb65</elementGuidId>
    <imagePath></imagePath>
    <name>chekhly_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>{"//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[3]/div[1]/a[1]":[".horizontal-menu__element[href='\\/category\\/chekhly-dlya-samsung']"]}</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>