<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>90525e4a-b05f-4f0e-b48e-a2eb4f7cde19</elementGuidId>
    <imagePath></imagePath>
    <name>svg_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>{"//body/div[3]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/button[1]/svg[1]":[".btn-lg .svg-inline--fa"]}</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>