<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fb3cabeb-da77-4fa4-bea5-5eebc3e49c4e</elementGuidId>
    <imagePath></imagePath>
    <name>ipad_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>{"//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[2]/ul[1]/li[2]/a[1]":[".horizontal-menu__element[href='\\/category\\/ipad-air-2-air']"]}</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>