<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a1c9232b-a42d-4835-83c0-6d548d720996</elementGuidId>
    <imagePath></imagePath>
    <name>podborki_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>{"//body/div[1]/div[3]/footer[1]/div[1]/div[1]/div[2]/ul[1]/li[4]/div[1]/a[1]":[".page-footer-menu__element[href='\\/category\\/podborki']"]}</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>